config/routes.rb
Rails.application.routes.draw do

  resources :facebook_images
  resources :errors, except: [:new, :edit] do
    get 'all_errors', on: :collection
  end
  resources :notifications do
    post 'push', on: :member
  end
  resources :auto_responders
  post 'technical_support/create'
  post 'device/create'

  devise_for :users

  resources :applications do
    get 'technical_works', on: :member
    resources :effects, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'assets_ios', on: :member
      get 'assets_android', on: :member
      get 'page_for_printing', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
    end
    resources :collections, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'medium_icon', on: :member
      get 'medium_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
      get 'pages_for_print', on: :member
      get 'extended_pages_for_print', on: :member
    end
    resources :commercials, except: :index do
      get 'image1', on: :member
      get 'image2', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :applications, only: :show do
        resources :collections, only: [], controller: 'collections' do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'medium_icon', on: :member
          get 'medium_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
        resources :effects, only: [] do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'assets_ios', on: :member
          get 'assets_android', on: :member
          get 'page_for_printing', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
      end
      resources :commercials, only: [] do
        get 'image1', on: :member
        get 'image2', on: :member
      end
      resources :errors, only: :create
      post 'devices/create'
      post 'technical_support/create'
      post 'send_email/create'
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'applications#index'
end

app/models/auto_responder.rb
class AutoResponder < ActiveRecord::Base
  has_many :applications, dependent: :nullify

  validates :name, presence: true
  validates :content, presence: true
end

app/controllers/auto_responders_controller.rb
class AutoRespondersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_auto_responder, only: [:show, :edit, :update, :destroy]

  # GET /auto_responders
  # GET /auto_responders.json
  def index
    @auto_responders = AutoResponder.all
  end

  # GET /auto_responders/1
  # GET /auto_responders/1.json
  def show
  end

  # GET /auto_responders/new
  def new
    @auto_responder = AutoResponder.new
  end

  # GET /auto_responders/1/edit
  def edit
  end

  # POST /auto_responders
  # POST /auto_responders.json
  def create
    @auto_responder = AutoResponder.new(auto_responder_params)

    respond_to do |format|
      if @auto_responder.save
        format.html { redirect_to @auto_responder, notice: 'Auto responder was successfully created.' }
        format.json { render :show, status: :created, location: @auto_responder }
      else
        format.html { render :new }
        format.json { render json: @auto_responder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auto_responders/1
  # PATCH/PUT /auto_responders/1.json
  def update
    respond_to do |format|
      if @auto_responder.update(auto_responder_params)
        format.html { redirect_to @auto_responder, notice: 'Auto responder was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto_responder }
      else
        format.html { render :edit }
        format.json { render json: @auto_responder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auto_responders/1
  # DELETE /auto_responders/1.json
  def destroy
    @auto_responder.destroy
    respond_to do |format|
      format.html { redirect_to auto_responders_url, notice: 'Auto responder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto_responder
      @auto_responder = AutoResponder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_responder_params
      params.require(:auto_responder).permit(:name, :content)
    end
end

app/helpers/auto_responders_helper.rb
module AutoRespondersHelper
end

app/views/auto_responders/_form.html.haml
= simple_form_for(@auto_responder) do |f|
  = f.error_notification
  - if f.object.errors.any?
    %ul
      - f.object.errors.full_messages.each do |msg|
        %li= msg

  .row.form-group
    .col-md-4
      = f.label :name
      = f.input_field :name, class: 'form-control'

  .row.form-group
    .col-md-12
      =f.input :content, as: :text, input_html: { class: 'form-control', rows: 20 }

  .row.form-group
    .col-md-12
      = f.button :submit
      = link_to 'Cancel', auto_responders_path, class: 'btn btn-default'

app/views/auto_responders/edit.html.haml
.container
  %h2
    Editing Auto responder

  = render 'form'

app/views/auto_responders/index.html.haml
.row
  .col-xs-10
    %h1= AutoResponder.model_name.human.pluralize
  .col-xs-2
    .title-control.pull-right.mt-20
      = link_to 'New', new_auto_responder_path, class: 'btn btn-default'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'Name'
      %th.thin-column= 'Actions'

  %tbody
    - @auto_responders.each do |auto_responder|
      %tr
        %td
          = link_to auto_responder.name, auto_responder
        %td.text-center
          .btn-group.btn-group-xs{ role: 'group' }
            %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
              = 'Select'
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Edit', edit_auto_responder_path(auto_responder)
              %li= link_to 'Destroy', auto_responder, method: :delete,
                class: 'bg-danger', data: { confirm: t('helpers.links.confirm') }

app/views/auto_responders/new.html.haml
.container
  %h2
    New Auto Responder

  = render 'form'

app/views/auto_responders/show.html.haml
.row.action-name-row-wrap
  .col-md-10
    %h1= @auto_responder.name

  .back-btn-col-wrap.mt-20
    = link_to 'Edit', edit_auto_responder_path(@auto_responder), class: 'btn btn-default'
    = link_to 'Back', auto_responders_path, class: 'btn btn-default'
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h4= 'Preview'
      .panel-body
        = @auto_responder.content.html_safe