config/routes.rb
Rails.application.routes.draw do

  resources :facebook_images
  resources :errors, except: [:new, :edit] do
    get 'all_errors', on: :collection
  end
  resources :notifications do
    post 'push', on: :member
  end
  resources :auto_responders
  post 'technical_support/create'
  post 'device/create'

  devise_for :users

  resources :applications do
    get 'technical_works', on: :member
    resources :effects, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'assets_ios', on: :member
      get 'assets_android', on: :member
      get 'page_for_printing', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
    end
    resources :collections, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'medium_icon', on: :member
      get 'medium_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
      get 'pages_for_print', on: :member
      get 'extended_pages_for_print', on: :member
    end
    resources :commercials, except: :index do
      get 'image1', on: :member
      get 'image2', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :applications, only: :show do
        resources :collections, only: [], controller: 'collections' do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'medium_icon', on: :member
          get 'medium_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
        resources :effects, only: [] do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'assets_ios', on: :member
          get 'assets_android', on: :member
          get 'page_for_printing', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
      end
      resources :commercials, only: [] do
        get 'image1', on: :member
        get 'image2', on: :member
      end
      resources :errors, only: :create
      post 'devices/create'
      post 'technical_support/create'
      post 'send_email/create'
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'applications#index'
end

app/models/application.rb
class Application < ActiveRecord::Base
  has_many :effects, dependent: :destroy
  has_many :collections, dependent: :destroy
  has_many :commercials, dependent: :destroy
  has_many :devices, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :auto_responder
  has_attached_file :certificate,
                    url: '/files/applications/:id/certificate.:extension',
                    path: ':rails_root/public/files/applications/:id/certificate.:extension'

  validates :name, presence: true
  validates_attachment_content_type :certificate, content_type: 'application/x-x509-ca-cert'

  def as_json(*)
    {
      effects: effects_as_json,
      collections: collections_as_json,
      commercials: commercials_as_json
    }
  end

  private

  def effects_as_json
    effects.avaliable.map { |effect| effect.as_json(only: effects_attributes) }
  end

  def collections_as_json
    collections.avaliable.map { |collection| collection.as_json(only: collections_attributes) }
  end

  def commercials_as_json
    commercials.map { |commercial| commercial.as_json(only: commercials_attributes) }
  end

  def collections_attributes
    [
      :id,
      :price,
      :name_ru,
      :name_en,
      :version,
      :description_ru,
      :description_en,
      :product,
      :printable,
      :app_version
    ]
  end

  def effects_attributes
    [:id, :name_ru, :name_en, :version, :description_ru, :description_en, :collection_id]
  end

  def commercials_attributes
    [:id, :collection_id, :title_ru, :description_ru, :price, :description_en, :title_en, :version, :url]
  end
end

app/controllers/api/v1/applications_controller.rb
module Api
  module V1
    class ApplicationsController < Api::BaseController
      before_action :set_application
      before_action :verify_token

      def show
        render json: @application
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include IndiaRedirectable
  india_redirectable /\/applications\/\d+\/(collections|effects)\/\d+\//

  rescue_from Postmark::InvalidMessageError do |exception|
    AutoRespondMailer.respond('cto@liveanimations.org', exception, Application.find(5)).deliver_now
    render nothing: true, status: 200
  end

  def after_sign_in_path_for(resource)
    applications_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :technical_works]
  load_and_authorize_resource except: :technical_works
  before_action :set_application, only: [:show, :edit, :update, :destroy, :technical_works]
  before_action :autoresponders, except: [:new, :edit]

  def index
    @applications = Application.all
  end

  def show
  end

  def new
    @application = Application.new
  end

  def edit
  end

  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def technical_works
    render json: {status: @application.technical_works}
  end

  private

  def autoresponders
    @autoresponders = AutoResponder.all
  end

  def set_application
    @application = Application.find(params[:id])
  end

  def application_params
    params.require(:application).permit(
      :name, :auto_responder_id, :certificate, :android_api_key, :technical_works, :version_android, :version_ios, :version_android
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_collection_table.html.haml
.row
  .col-xs-12.mt-20
    .title-control.pull-right.mb-10
      = link_to 'Create Collection', new_application_collection_path(@application), class: 'btn btn-default'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'Name RU'
      %th= 'Description'
      %th= 'Hide'
      %th.thin-column= 'Size'
      %th.thin-column= 'Version'
      %th.thin-column= 'Actions'

  %tbody
    - @application.collections.each do |collection|
      %tr
        %td
          = link_to collection.name_ru, application_collection_path(@application, collection)
        %td= collection.description_ru
        %td= collection.hide? ? 'Yes' : 'No'
        %td.text-center= collection.size
        %td.text-center= collection.version
        %td.text-center
          .btn-group.btn-group-xs{ role: 'group' }
            %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
              = 'Select'
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Edit', edit_application_collection_path(@application, collection)
              %li= link_to 'Destroy', application_collection_path(@application, collection), method: :delete,
                class: 'bg-danger', data: { confirm: 'Are you sure?' }

app/views/applications/_commercial_table.haml
.row
  .col-xs-12.mt-20
    .title-control.pull-right.mb-10
      = link_to 'Create Commercial', new_application_commercial_path(@application), class: 'btn btn-default'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'Title RU'
      %th= 'Title EN'
      %th= 'Description RU'
      %th= 'Description EN'
      %th.thin-column= 'Version'
      %th.thin-column= 'Price'
      %th.thin-column= 'Actions'

  %tbody
    - @application.commercials.each do |commercial|
      %tr
        %td= link_to commercial.title_ru, application_commercial_path(@application, commercial)
        %td= link_to commercial.title_en, application_commercial_path(@application, commercial)
        %td= commercial.description_ru
        %td= commercial.description_en
        %td.text-center= commercial.version
        %td.text-center= commercial.price
        %td.text-center
          .btn-group.btn-group-xs{ role: 'group' }
            %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
              = 'Select'
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Edit', edit_application_commercial_path(@application, commercial)
              %li= link_to 'Destroy', application_commercial_path(@application, commercial), method: :delete,
                class: 'bg-danger', data: { confirm: 'Are you sure?' }

app/views/applications/_effect_table.html.haml
.row
  .col-xs-12.mt-20
    .title-control.pull-right.mb-10
      = link_to 'Create Effect', new_application_effect_path(@application), class: 'btn btn-default'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'Name RU'
      %th= 'Description'
      %th= 'Hide'
      %th.thin-column= 'iOS'
      %th.thin-column= 'Android'
      %th.thin-column= 'Version'
      %th.thin-column= 'Actions'

  %tbody
    - @application.effects.each do |effect|
      %tr
        %td
          = link_to effect.name_ru, application_effect_path(@application, effect)
        %td= effect.description_ru
        %td= effect.hide? ? 'Yes' : 'No'
        %td.text-center= effect.ios_count_downloads
        %td.text-center= effect.android_count_downloads
        %td.text-center= effect.version
        %td.text-center
          .btn-group.btn-group-xs{ role: 'group' }
            %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
              = 'Select'
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Edit', edit_application_effect_path(@application, effect)
              %li= link_to 'Destroy', application_effect_path(@application, effect), method: :delete,
                class: 'bg-danger', data: { confirm: 'Are you sure?' }

app/views/applications/_form.html.haml
= simple_form_for(@application) do |f|
  = f.error_notification
  - if f.object.errors.any?
    %ul
      - f.object.errors.full_messages.each do |msg|
        %li= msg

  .row.form-group
    .col-md-6
      = f.label :name
      = f.input_field :name, class: 'form-control'

  .row.form-group
    .col-md-3
      = f.input :certificate, as: :file
    .col-md-3
      %h4= @application.certificate_file_name

  .row.form-group
    .col-md-6
      = f.label :android_api_key
      = f.input_field :android_api_key, class: 'form-control'

  .row.form-group
    .col-md-6
      = f.label :technical_works
      = f.input_field :technical_works, class: 'form-control'
  .row.form-group
    .col-md-6
      = f.label :version_ios
      = f.input_field :version_ios, class: 'form-control'

  .row.form-group
    .col-md-6
      = f.label :version_android
      = f.input_field :version_android, class: 'form-control'

  .row.form-group
    .col-md-6
      = f.association :auto_responder, auto_responders: @autoresponders, label_method: :name, value_method: :id, prompt: "Choose a Auto Responder"

  .row.form-group
    .col-md-12
      = f.button :submit
      = link_to 'Cancel', applications_path, class: 'btn btn-default'

app/views/applications/edit.html.haml
.container
  %h2
    Editing Application

  = render 'form'

app/views/applications/index.html.haml
.row
  .col-xs-10
    %h1= Application.model_name.human.pluralize
  .col-xs-2
    .title-control.pull-right.mt-20
      = link_to 'New', new_application_path, class: 'btn btn-default'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'Name'
      %th.thin-column= 'Actions'

  %tbody
    - @applications.each do |application|
      %tr
        %td
          = link_to application.name, application
        %td.text-center
          .btn-group.btn-group-xs{ role: 'group' }
            %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
              = 'Select'
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Edit', edit_application_path(application)
              %li= link_to 'Destroy', application, method: :delete,
                class: 'bg-danger', data: { confirm: t('helpers.links.confirm') }

app/views/applications/new.html.haml
.container
  %h2
    New Application

  = render 'form'

app/views/applications/show.html.haml
.row.action-name-row-wrap
  .col-md-11
    %h1
      = @application.name
      %span
        (
        = Device.where(application_id: @application.id).android.count
        )
  .back-btn-col-wrap.mt-20
    = link_to 'Back', applications_path
  .container
    %ul.nav.nav-tabs
      %li.active{role: 'presentation'}
        %a{'data-toggle': 'tab', href: '#collection_table'}
          = 'Collections'

      %li{role: 'presentation'}
        %a{'data-toggle': 'tab', href: '#effect_table'}
          = 'Effects'

      %li{role: 'presentation'}
        %a{'data-toggle': 'tab', href: '#commercial_table'}
          = 'Commercials'

    .tab-content.mt-10
      .tab-pane.active#collection_table= render 'collection_table'
      .tab-pane#effect_table= render 'effect_table'
      .tab-pane#commercial_table= render 'commercial_table'