config/routes.rb
Rails.application.routes.draw do

  resources :facebook_images
  resources :errors, except: [:new, :edit] do
    get 'all_errors', on: :collection
  end
  resources :notifications do
    post 'push', on: :member
  end
  resources :auto_responders
  post 'technical_support/create'
  post 'device/create'

  devise_for :users

  resources :applications do
    get 'technical_works', on: :member
    resources :effects, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'assets_ios', on: :member
      get 'assets_android', on: :member
      get 'page_for_printing', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
    end
    resources :collections, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'medium_icon', on: :member
      get 'medium_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
      get 'pages_for_print', on: :member
      get 'extended_pages_for_print', on: :member
    end
    resources :commercials, except: :index do
      get 'image1', on: :member
      get 'image2', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :applications, only: :show do
        resources :collections, only: [], controller: 'collections' do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'medium_icon', on: :member
          get 'medium_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
        resources :effects, only: [] do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'assets_ios', on: :member
          get 'assets_android', on: :member
          get 'page_for_printing', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
      end
      resources :commercials, only: [] do
        get 'image1', on: :member
        get 'image2', on: :member
      end
      resources :errors, only: :create
      post 'devices/create'
      post 'technical_support/create'
      post 'send_email/create'
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'applications#index'
end

app/models/facebook_image.rb
class FacebookImage < ActiveRecord::Base
  has_attached_file :image, styles: { medium: '300x300>', thumb: '140x140>' },
                    url: '/files/facebook_images/:id/image/:style/image.:extension',
                    path: ':rails_root/public/files/facebook_images/:id/image/:style/image.:extension'
  validates :name, presence: true
  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: ["application/pdf",
                                                           "application/zip",
                                                           "application/x-zip",
                                                           "application/x-zip-compressed",
                                                           "application/octet-stream",
                                                           "image/jpeg",
                                                           "image/jpg",
                                                           "image/png"
                                                          ]

  before_post_process :skip_for_zip

  def skip_for_zip
     ! %w(application/zip application/x-zip).include?(image_content_type)
  end
end

app/controllers/facebook_images_controller.rb
class FacebookImagesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :edit, :create, :update, :destroy]
  load_and_authorize_resource
  before_action :set_facebook_image, only: [:show, :edit, :update, :destroy]

  def index
    logger.info "Test logger"
    @facebook_images = FacebookImage.all
  end

  def show
  end

  def new
    @facebook_image = FacebookImage.new
  end

  def edit
  end

  def create
    @facebook_image = FacebookImage.new(facebook_image_params)

    respond_to do |format|
      if @facebook_image.save
        format.html { redirect_to @facebook_image, notice: 'Facebook image was successfully created.' }
        format.json { render :show, status: :created, location: @facebook_image }
      else
        format.html { render :new }
        format.json { render json: @facebook_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @facebook_image.update(facebook_image_params)
        format.html { redirect_to @facebook_image, notice: 'Facebook image was successfully updated.' }
        format.json { render :show, status: :ok, location: @facebook_image }
      else
        format.html { render :edit }
        format.json { render json: @facebook_image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @facebook_image.destroy
    respond_to do |format|
      format.html { redirect_to facebook_images_url, notice: 'Facebook image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facebook_image
      @facebook_image = FacebookImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facebook_image_params
      params.require(:facebook_image).permit(:name, :image)
    end
end

app/helpers/facebook_images_helper.rb
module FacebookImagesHelper
end

app/views/facebook_images/_form.html.haml
= simple_form_for(@facebook_image) do |f|
  = f.error_notification
  - if f.object.errors.any?
    %ul
      - f.object.errors.full_messages.each do |msg|
        %li= msg

  .row.form-group
    .col-md-4
      = f.label :name
      = f.input_field :name, class: 'form-control'

  .row.form-group
    .col-md-12
      = f.input :image, as: :file
    .col-md-12
      #image
        - if f.object.image_file_name
          = image_tag f.object.image.url(:thumb), class: 'img-rounded'

  .row.form-group
    .col-md-12
      = f.button :submit
      = link_to 'Cancel', facebook_images_path, class: 'btn btn-default'

app/views/facebook_images/edit.html.haml
.container
  %h2
    Editing Facebook Image

  = render 'form'

app/views/facebook_images/index.html.haml
.row
  .col-xs-10
    %h1= FacebookImage.model_name.human.pluralize
  .col-xs-2
    .title-control.pull-right.mt-20
      = link_to 'New', new_facebook_image_path, class: 'btn btn-default'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'Name'
      %th.thin-column= 'Actions'

  %tbody
    - @facebook_images.each do |facebook_image|
      %tr
        %td
          = link_to facebook_image.name, facebook_image
        %td.text-center
          .btn-group.btn-group-xs{ role: 'group' }
            %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
              = 'Select'
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Edit', edit_facebook_image_path(facebook_image)
              %li= link_to 'Destroy', facebook_image, method: :delete,
                class: 'bg-danger', data: { confirm: t('helpers.links.confirm') }

app/views/facebook_images/new.html.haml
.container
  %h2
    New Facebook Image

  = render 'form'

app/views/facebook_images/show.html.haml
.row.action-name-row-wrap
  .col-md-10
    %h1= @facebook_image.name

  .back-btn-col-wrap.mt-20
    = link_to 'Edit', edit_facebook_image_path(@facebook_image), class: 'btn btn-default'
    = link_to 'Back', facebook_images_path, class: 'btn btn-default'
  .col-md-12
    %h5= "Url: https://#{request.host_with_port}#{@facebook_image.image.url[0..-12]}"
  .col-md-12
    = image_tag @facebook_image.image.url(:original), class: 'img-rounded'