config/routes.rb
Rails.application.routes.draw do

  resources :facebook_images
  resources :errors, except: [:new, :edit] do
    get 'all_errors', on: :collection
  end
  resources :notifications do
    post 'push', on: :member
  end
  resources :auto_responders
  post 'technical_support/create'
  post 'device/create'

  devise_for :users

  resources :applications do
    get 'technical_works', on: :member
    resources :effects, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'assets_ios', on: :member
      get 'assets_android', on: :member
      get 'page_for_printing', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
    end
    resources :collections, except: :index do
      get 'small_icon', on: :member
      get 'small_icon_2', on: :member
      get 'medium_icon', on: :member
      get 'medium_icon_2', on: :member
      get 'large_icon', on: :member
      get 'large_icon_2', on: :member
      get 'dat', on: :member
      get 'xml', on: :member
      get 'pages_for_print', on: :member
      get 'extended_pages_for_print', on: :member
    end
    resources :commercials, except: :index do
      get 'image1', on: :member
      get 'image2', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :applications, only: :show do
        resources :collections, only: [], controller: 'collections' do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'medium_icon', on: :member
          get 'medium_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
        resources :effects, only: [] do
          get 'small_icon', on: :member
          get 'small_icon_2', on: :member
          get 'large_icon', on: :member
          get 'large_icon_2', on: :member
          get 'assets_ios', on: :member
          get 'assets_android', on: :member
          get 'page_for_printing', on: :member
          get 'dat', on: :member
          get 'xml', on: :member
        end
      end
      resources :commercials, only: [] do
        get 'image1', on: :member
        get 'image2', on: :member
      end
      resources :errors, only: :create
      post 'devices/create'
      post 'technical_support/create'
      post 'send_email/create'
    end
  end

  require 'sidekiq/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'applications#index'
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :application

  validates :name_ru, presence: true
  validates :text_ru, presence: true
  validates :name_en, presence: true
  validates :text_en, presence: true
  validates :application_id, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  before_action :set_notification, only: [:show, :edit, :update, :destroy, :push]

  def index
    @notifications = Notification.all
  end

  def show
  end

  def new
    @notification = Notification.new
  end

  def edit
  end

  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def push
    NotifyIosJob.perform_later(@notification.application_id, @notification)
    NotifyAndroidJob.perform_later(@notification.application_id, @notification)
    redirect_to @notification, notice: 'Notification was push.'
  end

  private

  def set_notification
    @notification = Notification.find(params[:id])
  end

  def notification_params
    params.require(:notification).permit(:name_ru, :name_en, :text_ru, :text_en, :application_id)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.haml
= simple_form_for(@notification) do |f|
  = f.error_notification
  - if f.object.errors.any?
    %ul
      - f.object.errors.full_messages.each do |msg|
        %li= msg

  .row.form-group
    .col-md-4
      = f.input :name_ru

  .row.form-group
    .col-md-4
      = f.input :name_en

  .row.form-group
    .col-md-4
      = f.input :text_ru, as: :text

  .row.form-group
    .col-md-4
      = f.input :text_en, as: :text

  .row.form-group
    .col-md-4
      = f.association :application

  .row.form-group
    .col-md-12
      = f.button :submit
      = link_to 'Cancel', notifications_path, class: 'btn btn-default'

app/views/notifications/edit.html.haml
.container
  %h2
    Editing Notification

  = render 'form'

app/views/notifications/index.html.haml
.row
  .col-xs-10
    %h1= Notification.model_name.human.pluralize
  .col-xs-2
    .title-control.pull-right.mt-20
      = link_to 'New', new_notification_path, class: 'btn btn-default'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th= 'Name RU'
      %th= 'Name EN'
      %th= 'Text RU'
      %th= 'Text EN'
      %th= 'Application'
      %th.thin-column= 'Actions'

  %tbody
    - @notifications.each do |notification|
      %tr
        %td= link_to notification.name_ru, notification
        %td= link_to notification.name_en, notification
        %td= notification.text_ru
        %td= notification.text_en
        %td= notification.application.name
        %td.text-center
          .btn-group.btn-group-xs{ role: 'group' }
            %button.btn.btn-default.dropdown-toggle{ data: { toggle: 'dropdown' } }
              = 'Select'
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Push', push_notification_path(notification),
                  method: :post,
                  data: { confirm: 'Do you really want to send this notification to all users?' }
              %li= link_to 'Edit', edit_notification_path(notification)
              %li= link_to 'Destroy', notification, method: :delete,
                class: 'bg-danger', data: { confirm: t('helpers.links.confirm') }

app/views/notifications/new.html.haml
.container
  %h2
    New Notification

  = render 'form'

app/views/notifications/show.html.haml
.row.action-name-row-wrap
  .col-md-10
    %h1= @notification.name_ru || @notification.name_en

  .back-btn-col-wrap.mt-20
    = link_to 'Push',
      push_notification_path(@notification),
      method: :post,
      class: 'btn btn-primary',
      data: { confirm: 'Do you really want to send this notification to all users?' }
    = link_to 'Back', notifications_path, class: 'btn btn-default'
  .col-md-6
    .panel.panel-default
      .panel-body
        = @notification.text_ru
  .col-md-6
    .panel.panel-default
      .panel-body
        = @notification.text_en

  .col-md-10
    %p
      %span.h4= 'Application: '
      = @notification.application.name